USE EmmisionsDW

DROP TABLE IF EXISTS dw.DIM_TIME;
DROP TABLE IF EXISTS dw.DIM_COUNTRY;
DROP TABLE IF EXISTS dw.DIM_SIZE
DROP TABLE IF EXISTS dw.DIM_REGION
DROP TABLE IF EXISTS dw.FACT_EMISSION;